export const TOGGLE_ALL_TODOS_STATUS = {
  SUCCESS: 'TOGGLE_ALL_TODOS_STATUS_SUCCESS',
  REQUEST: 'TOGGLE_ALL_TODOS_STATUS_REQUEST',
  FAIL: 'TOGGLE_ALL_TODOS_STATUS_FAIL',
};

export const CHANGE_TODO = {
  SUCCESS: 'CHANGE_TODO_SUCCESS',
  REQUEST: 'CHANGE_TODO_REQUEST',
  FAIL: 'CHANGE_TODO_FAIL',
};

export const CLEAR_ALL_COMPLETED = {
  SUCCESS: 'CLEAR_ALL_COMPLETED_SUCCESS',
  REQUEST: 'CLEAR_ALL_COMPLETED_REQUEST',
  FAIL: 'CLEAR_ALL_COMPLETED_FAIL',
};

export const ADD_TODO = {
  SUCCESS: 'ADD_TODO_SUCCESS',
  REQUEST: 'ADD_TODO_REQUEST',
  FAIL: 'ADD_TODO_FAIL',
};

export const REMOVE_TODO = {
  SUCCESS: 'REMOVE_TODO_SUCCESS',
  REQUEST: 'REMOVE_TODO_REQUEST',
  FAIL: 'REMOVE_TODO_FAIL',
};

export const SET_TODO_VALIDATION_ERROR = {
  SUCCESS: 'SET_TODO_VALIDATION_ERROR_SUCCESS',
  REQUEST: 'SET_TODO_VALIDATION_ERROR_REQUEST',
  FAIL: 'SET_TODO_VALIDATION_ERROR_FAIL',
};

export const SET_FILTER_TYPE = {
  SUCCESS: 'SET_FILTER_TYPE_SUCCESS',
  REQUEST: 'SET_FILTER_TYPE_REQUEST',
  FAIL: 'SET_FILTER_TYPE_FAIL',
};
