export const LOGIN = {
  SUCCESS: 'LOGIN_SUCCESS',
  FAIL: 'LOGIN_FAIL',
  REQUEST: 'LOGIN_REQUEST',
};

export const LOGOUT = {
  SUCCESS: 'LOGOUT_SUCCESS',
  FAIL: 'LOGOUT_FAIL',
  REQUEST: 'LOGOUT_REQUEST',
};

export const SET_TOKEN = {
  SUCCESS: 'SET_TOKEN_SUCCESS',
  FAIL: 'SET_TOKEN_FAIL',
  REQUEST: 'SET_TOKEN_REQUEST',
};
